dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: simple-gateway
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: simple-greeter-gateway
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: simple-greeter-one
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: simple-greeter-two
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: simple-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: web-service-test
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
