dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: test-vertx-web
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.8
- name: vert-grpc-buildpack-test
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: vert-web-buildpack-test
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
