dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: test-vertx-grpc
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: test-vertx-web
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: vertx-web-quickstart-test2
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
